"""ASS字幕ファイル出力ロジック."""

from __future__ import annotations

import math
from collections.abc import Callable
from pathlib import Path

import cv2
import numpy as np

from ascii_core import (
    AsciiParams,
    apply_mask_to_ascii_lines,
    apply_mask_to_colors,
    count_color_runs,
    frame_to_ascii_result,
)


# YouTube字幕が受け付ける要素数(spans)の実測上限の目安。
# 実績: 267,830 spans=アップ可 / 375,551 spans=不可。安全側に約27万を境界とする。
YT_SPAN_LIMIT = 270_000

# 列数の実用上限。YouTube字幕のフォントには最小サイズ(YTSubConverterの sz=0 床)があり、
# これを超えると文字が縮みきれず横にあふれてレイアウトが崩れる。実測で約82列が境界。
YT_MAX_COLS = 82


def estimate_total_spans(
    video_path: Path,
    params: AsciiParams,
    start_sec: float,
    dur_sec: float | None,
    samples: int = 4,
) -> int:
    """エクスポート結果の総 ytt spans 数をサンプリングで概算する。

    数フレームの色ラン数を測り、フレーム数で外挿。各行のラッパ<s>分(約2/行)を加味。
    YouTube字幕の要素数上限に引っかかるかの事前警告に使う。
    """
    cap = cv2.VideoCapture(str(video_path))
    if not cap.isOpened():
        return 0
    try:
        fps = max(params.fps, 0.1)
        dt = 1.0 / fps
        if dur_sec is None:
            vid_fps = cap.get(cv2.CAP_PROP_FPS) or 0.0
            vid_frames = cap.get(cv2.CAP_PROP_FRAME_COUNT) or 0.0
            vid_len = (vid_frames / vid_fps) if vid_fps > 0 else 0.0
            n_frames = max(1, int(math.ceil(max(vid_len - start_sec, 0.0) / dt)))
        else:
            n_frames = max(1, int(math.ceil(max(dur_sec, 0.0) / dt)))

        runs: list[int] = []
        for i in range(max(1, samples)):
            frac = i / max(1, samples - 1) if samples > 1 else 0.0
            t = start_sec + frac * (n_frames - 1) * dt
            cap.set(cv2.CAP_PROP_POS_MSEC, t * 1000.0)
            ok, frame = cap.read()
            if not ok:
                continue
            res = frame_to_ascii_result(frame, params)
            runs.append(count_color_runs(res.lines, res.colors))
        if not runs:
            return 0
        avg = sum(runs) / len(runs)
        overhead = 2 * params.rows  # 行ごとのラッパ<s>分
        return int((avg + overhead) * n_frames)
    finally:
        cap.release()


ASS_HEADER = """[Script Info]
; Script generated by ASScii
Title: ASScii Export
ScriptType: v4.00+
WrapStyle: 0
ScaledBorderAndShadow: yes
YCbCr Matrix: TV.601
PlayResX: {play_res_x}
PlayResY: {play_res_y}

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Default,{fontname},15,&H00F5F5F5,&H000000FF,&H00101010,&H80101010,0,0,0,0,100,100,0,0,1,2,0,5,20,20,20,1

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
"""


def sec_to_ass_time(t: float) -> str:
    if t < 0:
        t = 0
    h = int(t // 3600)
    t -= h * 3600
    m = int(t // 60)
    t -= m * 60
    s = int(t)
    cs = int(round((t - s) * 100))
    if cs == 100:
        s += 1
        cs = 0
    return f"{h}:{m:02d}:{s:02d}.{cs:02d}"


WORD_JOINER = "\u2060"


def escape_ass_text(s: str) -> str:
    result: list[str] = []

    for ch in s:
        if ch == "\n":
            result.append(f"\\\\{WORD_JOINER}n")
            continue
        if ch == " ":
            result.append("\\h")
            continue
        if ch == "\\":
            result.append(f"\\\\{WORD_JOINER}")
            continue
        if ch in {"{", "}"}:
            result.append("\\" + ch)
        else:
            result.append(ch)
    return "".join(result)


def _ass_color_tag(rgb: np.ndarray | tuple[int, int, int]) -> str:
    r, g, b = int(rgb[0]), int(rgb[1]), int(rgb[2])
    return f"{{\\c&H{b:02X}{g:02X}{r:02X}&}}"


def lines_to_ass_text(lines: list[str], colors: np.ndarray | None = None) -> str:
    if colors is None:
        return "\\N".join(escape_ass_text(line) for line in lines)

    parts: list[str] = []
    for r, line in enumerate(lines):
        row_colors = colors[r] if r < colors.shape[0] else None
        if row_colors is None:
            parts.append(escape_ass_text(line))
        else:
            if len(line) == 0:
                parts.append("")
                continue
            run_color = row_colors[0]
            run_start = 0
            for c, ch in enumerate(line):
                col_val = row_colors[c] if c < len(row_colors) else run_color
                if c == 0:
                    run_color = col_val
                    continue
                if not np.array_equal(col_val, run_color):
                    segment = line[run_start:c]
                    parts.append(_ass_color_tag(run_color) + escape_ass_text(segment))
                    run_color = col_val
                    run_start = c
            segment = line[run_start:]
            parts.append(_ass_color_tag(run_color) + escape_ass_text(segment))
        if r != len(lines) - 1:
            parts.append("\\N")
    return "".join(parts)


def export_ass(
    video_path: Path,
    out_path: Path,
    params: AsciiParams,
    start_sec: float,
    dur_sec: float | None,
    pos_x: float,
    pos_y: float,
    fontname: str,
    fontsize: int,
    play_res_x: int,
    play_res_y: int,
    mask_lookup: Callable[[int], np.ndarray | None] | None = None,
) -> None:
    cap = cv2.VideoCapture(str(video_path))
    if not cap.isOpened():
        raise RuntimeError("Could not open video for export.")

    fps = max(params.fps, 0.1)
    dt = 1.0 / fps
    target_frames: int | None = None
    if dur_sec is not None:
        target_frames = int(math.ceil(max(dur_sec, 0.0) / dt))

    header = ASS_HEADER.format(
        play_res_x=play_res_x,
        play_res_y=play_res_y,
        fontname=fontname,
    )

    with open(out_path, "w", encoding="utf-8") as f:
        f.write(header)

        i = 0
        while True:
            if target_frames is not None and i >= target_frames:
                break
            t0 = start_sec + i * dt
            t1 = start_sec + (i + 1) * dt

            cap.set(cv2.CAP_PROP_POS_MSEC, t0 * 1000.0)
            ok, frame = cap.read()
            if not ok:
                break
            frame_idx = None
            try:
                pos = cap.get(cv2.CAP_PROP_POS_FRAMES)
            except Exception:
                pos = None
            if pos is not None and not math.isnan(float(pos)):
                frame_idx = max(0, int(pos) - 1)

            ascii_result = frame_to_ascii_result(frame, params)
            lines = ascii_result.lines
            colors = ascii_result.colors
            mask = None
            if mask_lookup is not None and frame_idx is not None:
                mask = mask_lookup(frame_idx)
                if mask is not None and mask.shape == (params.rows, params.cols):
                    lines = apply_mask_to_ascii_lines(lines, mask)
                    colors = apply_mask_to_colors(colors, mask)
            txt = lines_to_ass_text(lines, colors)

            fs_value = max(1, int(round(fontsize)))
            ass_line = (
                f"Dialogue: 0,{sec_to_ass_time(t0)},{sec_to_ass_time(t1)},"
                f"Default,,0,0,0,,{{\\an5\\fs{fs_value}\\pos({pos_x:.3f},{pos_y:.3f})}}{txt}\n"
            )
            f.write(ass_line)
            i += 1

    cap.release()
